language: node_js

services:
    - postgresql

addons:
    postgresql: "12.1"

node_js:
    - node

before_install:
    - sudo apt-get update
    - sudo /etc/init.d/postgresql stop
    - sudo /etc/init.d/postgresql start 12.1

before_script:
    - psql --version
    - psql -c "CREATE DATABASE bitsky;" -U postgres
    - psql -c "CREATE DATABASE bitsky_test;" -U postgres
    - psql -c "CREATE ROLE admin LOGIN SUPERUSER PASSWORD 'admin';" -U postgres
    - psql -c "CREATE ROLE test LOGIN SUPERUSER PASSWORD 'test';" -U postgres

    - yarn
    - yarn danger ci

    - cd projects/api && yarn
